name: main.yml
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  lint:
    name: Linting Job
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
