name: main.yml

on:
  pull_request:
    branches: [main]

  push:
    branches: [main]

jobs:
  lint:
    name: Linting Job
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
        - name: Checkout repository
        uses: actions/checkout@v2
        - name: Install node v14
        uses: actions/setup-node@v2
        - name: Install eslint
        run: npm install eslint
        - name: Run ES linting
        run: npm run lint